#!/bin/sh
#
# Writes the final sources.list file
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
RELEASE="trixie"

cat << EOF > $CHROOT/etc/apt/sources.list
# BlankOn Linux Package Repository
deb http://arsip-dev.blankonlinux.id/dev verbeek main restricted extras
EOF

exit 0
